Repository skupperproject/skupper-router, pull requests merged in 2022-04, with the labels that each got.

#288 Fixed #282: tcp connection must use tcp connector reference count
  src/adaptors/tcp_adaptor.c
  src/adaptors/tcp_adaptor.h
Labels: bug

#287 Added latency measurements to TCP flow logs.
  include/qpid/dispatch/protocol_log.h
  src/adaptors/tcp_adaptor.c
  src/protocol_log.c
Labels: enhancement

#100 New version shutdown.adoc initial checkin
  docs/notes/shutdown.adoc
Labels: documentation

#284 ISSUE-196: Enable TLS on http2 adaptors.
  CMakeLists.txt
  include/qpid/dispatch/connection_manager.h
  include/qpid/dispatch/dispatch.h
  python/skupper_router/management/skrouter.json
  src/CMakeLists.txt
  src/adaptors/http2/http2_adaptor.c
  src/adaptors/http2/http2_adaptor.h
  src/adaptors/http_common.c
  src/adaptors/http_common.h
  src/alloc_pool.c
  src/connection_manager.c
  src/dispatch.c
  tests/CMakeLists.txt
  tests/config-2/gencerts.sh
  tests/friendship_server.py
  tests/http2_server.py
  tests/http2_slow_q2_server.py
  tests/ssl_certs/gencerts.sh
  tests/ssl_certs/server-private-key-no-pass.pem
  tests/system_test.py
  tests/system_tests_grpc.py
  tests/system_tests_http2.py
  tests/system_tests_http2_tls.py
  tests/system_tests_ssl.py
Labels: enhancement

#307 Fix `QDROUTERD_RUNNER` CMake option parsing to be shell-like
  README.adoc
  tests/system_test.py
Labels: documentation, enhancement
